prefix=/usr/local
exec_prefix=${prefix}
bindir=${exec_prefix}/bin
libdir=${exec_prefix}/lib
includedir=${prefix}/include
ICSPATH=/Users/e35480/projects/misc/ics-2.1.experimental
CC=clang
CXX=clang++
AR=ar
RANLIB=ranlib
SED=sed
OCAMLC=ocamlc
OCAMLOPT=ocamlopt
OCAMLMKTOP=ocamlmktop
OCAMLMKLIB=ocamlmklib
OCAMLDEP=ocamldep
OCAMLLEX=ocamllex
OCAMLYACC=ocamlyacc
OCAMLDOC=ocamldoc
CFLAGS=-O3 -DNDEBUG
CXXFLAGS=-O3 -DNDEBUG
CPPFLAGS=
LDFLAGS=
LIBS=
posixos=darwin
SET_MAKE=
