#!/bin/sh
#
# Script for starting ICS 
#

ICSPATH=/Users/e35480/projects/misc/ics-2.1.experimental
ARCH=`$ICSPATH/config.guess`

if [ "$1" = "-bytecode" ]; then
  shift
  cd $ICSPATH/obj/$ARCH
  exec $ICSPATH/bin/$ARCH/ics.byte $@
else
  exec $ICSPATH/bin/$ARCH/ics $@
fi
