(*
 * Legacy proprietary license boilerplate removed for the open-source release.
 *)

(** Inference system for the theory of nonlinear multiplication. 

  @author Harald Ruess
  @author N. Shankar
*)


module Ops: Can.OPS
  (** Various operations with a set of flat equalities of the
    form [u = x * y] as context. *)


module Infsys: (Infsys.EQ with type e = Solution.Set.t)
  (** Inference system for nonlinear multiplication as 
    an extension of the AC inference system {!Ac.Make}
    instantiated with the signature {!Pprod.Sig} of nonlinear
    multiplication.  

    A nonlinear {i context} consists of equalities of the form [x = y*z] 
    with [x], [y], [z] variables.
    
    The following invariants are maintained.
    - Right-hand sides of context equalities [x = a] are kept in 
    canonical form.  That is, if the variable equality [y = z]
    has been merged using [merge], then the noncanonical [y]
    is not appearing on any right-hand side. 
    - Also, if [x = a] and [y = b] in a context, then the 
    variables [x] and [y] are different (that is, they are not {!Term.eq})
    - If [u = y * v] in a context, then [y] is always {i atomic} in the 
    sense that it is an {i original} variable from one of the arguments
    of [process] or [name], whereas [u], [v] may be {i generated}
    variables.
    
    Forward chaining is used to keep contexts {i confluent}
    - [x' = y * v], [z = x*u], [x =v x'] ==> [z = y * v * u]
    with [=v] generated by the current variable partitioning.
    
    In addition to AC inferences, this inference system
    - deduces, for example, [x >= 0] if [x = y * z] and [y, z >= 0]
    - branches on [x = 0] or [a = 1] if [x = x * a]. 
  *)

